# -*- coding: utf-8 -*-
"""problem006.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/136QjCyMn0AxJ4PZxj7iYCtJ_s0JLYC5T
"""

# 006. Move Zeros to End
def move_zeros_bruteforce(arr):
    res = [x for x in arr if x != 0]
    res.extend([0] * (len(arr) - len(res)))
    return res

def move_zeros_optimized(arr):
    write = 0
    for read in range(len(arr)):
        if arr[read] != 0:
            arr[write] = arr[read]
            write += 1
    while write < len(arr):
        arr[write] = 0
        write += 1
    return arr

print(move_zeros_bruteforce([0,1,0,3,12]))
print(move_zeros_optimized([0,1,0,3,12]))