# -*- coding: utf-8 -*-
"""problem008.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TUOcbcKNcuEr7beIS_LvZGgARm6L0MaK
"""

# 008. Find Missing Number
def missing_number_bruteforce(nums):
    n = len(nums)
    seen = [False] * (n + 1)
    for x in nums:
        seen[x] = True
    for i in range(n + 1):
        if not seen[i]:
            return i

def missing_number_optimized(nums):
    n = len(nums)
    return n * (n + 1) // 2 - sum(nums)

print(missing_number_bruteforce([3, 0, 1]))
print(missing_number_optimized([3, 0, 1]))