# -*- coding: utf-8 -*-
"""problem016.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QogPZnjoAxvAbf_bxyeYp3kxcXEOyzRS
"""

# P016: Maximum product subarray
# Bruteforce: try all subarrays (O(n^2))
def max_prod_subarray_bruteforce(nums):
    best = -float('inf')
    for i in range(len(nums)):
        prod = 1
        for j in range(i, len(nums)):
            prod *= nums[j]
            best = max(best, prod)
    return best

# Optimized: track max/min product up to current (O(n))
def max_prod_subarray_optimized(nums):
    cur_max = cur_min = best = nums[0]
    for x in nums[1:]:
        if x < 0:
            cur_max, cur_min = cur_min, cur_max
        cur_max = max(x, cur_max * x)
        cur_min = min(x, cur_min * x)
        best = max(best, cur_max)
    return best

# Test
arr1 = [2, 3, -2, 4]
arr2 = [-2, 0, -1]
print("P016 bruteforce arr1:", max_prod_subarray_bruteforce(arr1))
print("P016 optimized  arr1:", max_prod_subarray_optimized(arr1))
print("P016 optimized  arr2:", max_prod_subarray_optimized(arr2))