# -*- coding: utf-8 -*-
"""problem003.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SAcDInq0tEyuOIgQ5954RbjjEsUJJl1t
"""

def is_sorted(arr):
    for i in range(len(arr) - 1):
        if arr[i] > arr[i + 1]:
            return False
    return True

print(is_sorted([1, 2, 3, 4]))
print(is_sorted([3, 2, 1]))

