# -*- coding: utf-8 -*-
"""problem007.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vuSorSyQMa4Qswimz-44aurPJENGwzVa
"""

# 007. Linear Search
def linear_search(arr, target):
    for i in range(len(arr)):
        if arr[i] == target:
            return i
    return -1

print(linear_search([2, 4, 6, 8], 6))
print(linear_search([2, 4, 6, 8], 5))