# -*- coding: utf-8 -*-
"""problem014.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15l72RUTgtQ5_WuPrjDr18gEApaKf_ycL
"""

# P014: Longest consecutive sequence
# Bruteforce: sort + linear scan (O(n log n))
def longest_consecutive_bruteforce(nums):
    if not nums: return 0
    nums = sorted(set(nums))
    longest = 1
    cur = 1
    for i in range(1, len(nums)):
        if nums[i] == nums[i-1] + 1:
            cur += 1
        else:
            longest = max(longest, cur)
            cur = 1
    return max(longest, cur)

# Optimized: use hash set (O(n))
def longest_consecutive_optimized(nums):
    numset = set(nums)
    longest = 0
    for n in numset:
        if n - 1 not in numset:  # sequence start
            cur = 1
            nxt = n + 1
            while nxt in numset:
                cur += 1
                nxt += 1
            longest = max(longest, cur)
    return longest

# Test
l1 = [100, 4, 200, 1, 3, 2]
l2 = [0,3,7,2,5,8,4,6,0,1]
print("P014 bruteforce:", longest_consecutive_bruteforce(l1))
print("P014 optimized :", longest_consecutive_optimized(l2))