# -*- coding: utf-8 -*-
"""problem009.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qvvm_6Wlpyi-ez9Cl17duJLAb3hxtV7X
"""

# 009. Maximum Consecutive Ones
def max_consec_ones_bruteforce(arr):
    best = 0
    for i in range(len(arr)):
        count = 0
        j = i
        while j < len(arr) and arr[j] == 1:
            count += 1
            j += 1
        best = max(best, count)
    return best

def max_consec_ones_optimized(arr):
    best = curr = 0
    for x in arr:
        if x == 1:
            curr += 1
            best = max(best, curr)
        else:
            curr = 0
    return best

print(max_consec_ones_bruteforce([1,1,0,1,1,1]))
print(max_consec_ones_optimized([1,1,0,1,1,1]))