# -*- coding: utf-8 -*-
"""problem012.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GdA87ACZbPUGkcy5fflqmWHrDkzro3kb
"""

# P012_python.py

from typing import List

def brute_force_max_profit(prices: List[int]) -> int:
    """
    Brute force: check every buy-sell pair.
    Time: O(n^2), Space: O(1)
    """
    n = len(prices)
    max_profit = 0
    for i in range(n - 1):
        buy = prices[i]
        for j in range(i + 1, n):
            sell = prices[j]
            profit = sell - buy
            if profit > max_profit:
                max_profit = profit
    return max_profit


def optimal_max_profit(prices: List[int]) -> int:
    """
    Optimal one-pass:
    Keep track of min price seen so far and best profit.
    Time: O(n), Space: O(1)
    """
    if not prices:
        return 0

    min_price = float('inf')
    max_profit = 0

    for price in prices:
        # If current price gives better sell profit, update
        if price - min_price > max_profit:
            max_profit = price - min_price
        # Update min_price after checking profit for current day
        if price < min_price:
            min_price = price

    return max_profit


if __name__ == "__main__":
    # Example 1
    arr1 = [10, 7, 5, 8, 11, 9]
    print("Example 1")
    print("Brute force result:", brute_force_max_profit(arr1))  # expected 6
    print("Optimal result:    ", optimal_max_profit(arr1))      # expected 6
    print()

    # Example 2
    arr2 = [5, 4, 3, 2, 1]
    print("Example 2")
    print("Brute force result:", brute_force_max_profit(arr2))  # expected 0
    print("Optimal result:    ", optimal_max_profit(arr2))      # expected 0
    print()

    # Extra tests
    print("Edge cases")
    print("Empty list:", optimal_max_profit([]))     # 0
    print("Single day:", optimal_max_profit([7]))   # 0
    print("Increasing:", optimal_max_profit([1,2,3,4,5]))  # 4 (buy 1 sell 5)