# -*- coding: utf-8 -*-
"""problem013.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19UfKmNT8YYs99Wv8SmhxAK6h8wyMvumE
"""

# P013: Leaders in array
# Bruteforce: check for each element (O(n^2))
def leaders_bruteforce(arr):
    n = len(arr)
    res = []
    for i in range(n):
        right_max = max(arr[i+1:], default=-float('inf'))
        if arr[i] > right_max:
            res.append(arr[i])
    return res

# Optimized: traverse from right (O(n))
def leaders_optimized(arr):
    n = len(arr)
    res = []
    max_right = -float('inf')
    for i in range(n-1, -1, -1):
        if arr[i] > max_right:
            res.append(arr[i])
            max_right = arr[i]
    return res[::-1]

# Test
nums = [10, 22, 12, 3, 0, 6]
print("P015 bruteforce:", leaders_bruteforce(nums))
print("P015 optimized :", leaders_optimized(nums))