# -*- coding: utf-8 -*-
"""problem005.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VfcLyCpsGUAEhLoaysw33jqpuX2JYpnM
"""

# 005. Left Rotate Array by One
def left_rotate(arr):
    if not arr:
        return arr
    first = arr[0]
    for i in range(len(arr) - 1):
        arr[i] = arr[i + 1]
    arr[-1] = first
    return arr

print(left_rotate([1, 2, 3, 4, 5]))