# -*- coding: utf-8 -*-
"""problem004.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TldykHR27gDRMQbFU2NfhxXycfb9kADW
"""

# 004. Remove Duplicates from Sorted Array
def remove_dupes_bruteforce(arr):
    unique = []
    for x in arr:
        if not unique or unique[-1] != x:
            unique.append(x)
    return len(unique)

def remove_dupes_optimized(arr):
    if not arr:
        return 0
    write = 1
    for read in range(1, len(arr)):
        if arr[read] != arr[read - 1]:
            arr[write] = arr[read]
            write += 1
    return write

print(remove_dupes_bruteforce([1,1,2,2,3,3]))
print(remove_dupes_optimized([1,1,2,2,3,3]))