# -*- coding: utf-8 -*-
"""problem017.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ItDZKjAueplsJvQMVvtJ0FkEU5BBaeP
"""

# P017: Union of two sorted arrays
# Bruteforce: merge and unique-sort (O((n+m) log(n+m)))
def union_bruteforce(a, b):
    return sorted(set(a + b))

# Optimized: two-pointer merge (O(n+m))
def union_optimized(a, b):
    i = j = 0
    res = []
    while i < len(a) and j < len(b):
        if a[i] < b[j]:
            if not res or res[-1] != a[i]:
                res.append(a[i])
            i += 1
        elif b[j] < a[i]:
            if not res or res[-1] != b[j]:
                res.append(b[j])
            j += 1
        else:
            if not res or res[-1] != a[i]:
                res.append(a[i])
            i += 1
            j += 1
    while i < len(a):
        if not res or res[-1] != a[i]:
            res.append(a[i])
        i += 1
    while j < len(b):
        if not res or res[-1] != b[j]:
            res.append(b[j])
        j += 1
    return res

# Test
a1 = [1, 2, 4, 5, 6]
b1 = [2, 3, 5, 7]
print("P017 bruteforce:", union_bruteforce(a1, b1))
print("P017 optimized :", union_optimized(a1, b1))