# -*- coding: utf-8 -*-
"""problem015.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v1H2JWJxblXPjy_m85QhgkmALYoPUAO_
"""

# P015: Count subarrays with given sum
# Bruteforce: check all subarrays (O(n^2))
def count_subarrays_bruteforce(arr, target):
    n = len(arr)
    count = 0
    for i in range(n):
        s = 0
        for j in range(i, n):
            s += arr[j]
            if s == target:
                count += 1
    return count

# Optimized: prefix sum + hashmap (O(n))
def count_subarrays_optimized(arr, target):
    pref = 0
    seen = {0: 1}
    count = 0
    for x in arr:
        pref += x
        if (pref - target) in seen:
            count += seen[pref - target]
        seen[pref] = seen.get(pref, 0) + 1
    return count

# Test
arr = [1, 1, 1]
target = 2
print("P015 bruteforce:", count_subarrays_bruteforce(arr, target))
print("P015 optimized :", count_subarrays_optimized(arr, target))

arr2 = [3,4,7,2,-3,1,4,2]
target2 = 7
print("P015 optimized test2:", count_subarrays_optimized(arr2, target2))