# -*- coding: utf-8 -*-
"""problem010.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13ICJflLCR2pnpgEc5AKOLUwQGNTKNx-n
"""

# 010. Majority Element (> n/2)
def majority_bruteforce(arr):
    n = len(arr)
    counts = {}
    for x in arr:
        counts[x] = counts.get(x, 0) + 1
        if counts[x] > n // 2:
            return x

def majority_optimized(arr):
    candidate = None
    count = 0
    for x in arr:
        if count == 0:
            candidate = x
            count = 1
        elif x == candidate:
            count += 1
        else:
            count -= 1
    return candidate

print(majority_bruteforce([2,2,1,1,1,2,2]))
print(majority_optimized([2,2,1,1,1,2,2]))