# -*- coding: utf-8 -*-
"""problem011.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gPVKbJqS8WCrocSRRsquyqMOD5HKonLT
"""

# P011: Maximum subarray sum
# Bruteforce: check all subarrays (O(n^2))
def max_subarray_bruteforce(arr):
    best = -float('inf')
    for i in range(len(arr)):
        s = 0
        for j in range(i, len(arr)):
            s += arr[j]
            if s > best: best = s
    return best

# Optimized: Kadane’s algorithm (O(n))
def max_subarray_optimized(arr):
    best = arr[0]
    cur = arr[0]
    for x in arr[1:]:
        cur = max(x, cur + x)
        best = max(best, cur)
    return best

# Test
arr = [-2, 1, -3, 4, -1, 2, 1, -5, 4]
print("P011 bruteforce:", max_subarray_bruteforce(arr))
print("P011 optimized :", max_subarray_optimized(arr))