# -*- coding: utf-8 -*-
"""problem002.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/144qYwemnh_PjdD1I_8QRSCe8C6ZoHT6g
"""

# 002. Second Smallest and Second Largest
def second_small_large_bruteforce(arr):
    if len(arr) < 2:
        return -1, -1
    arr = sorted(arr)
    return arr[1], arr[-2] if len(arr) > 1 else (-1, -1)

def second_small_large_optimized(arr):
    if len(arr) < 2:
        return -1, -1
    min1 = min2 = float('inf')
    max1 = max2 = float('-inf')
    for x in arr:
        if x < min1:
            min2, min1 = min1, x
        elif x < min2 and x != min1:
            min2 = x
        if x > max1:
            max2, max1 = max1, x
        elif x > max2 and x != max1:
            max2 = x
    return (min2 if min2 != float('inf') else -1,
            max2 if max2 != float('-inf') else -1)

print(second_small_large_bruteforce([5, 1, 9, 2, 9]))
print(second_small_large_optimized([5, 1, 9, 2, 9]))

