# -*- coding: utf-8 -*-
"""problem001.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Zc7MhUjVu7SdmGB90ax3F40QciOaOMl
"""

# 001. Largest Element
def largest(arr):
    m = float('-inf')
    for x in arr:
        if x > m:
            m = x
    return m

print(largest([3, 7, 2, 9, 1]))

