# -*- coding: utf-8 -*-
"""Problem001.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WbXaPflBRR7IAYWPEOCgqvdmqYmcinIB
"""

# Breadth First Search (BFS): Level Order Traversal

# Problem Statement: Given an undirected graph, return a vector of all nodes by traversing the graph using breadth-first search (BFS).

# Pre-req: Graph Representation, Queue STL


from collections import deque

def bfs(graph, start):
    visited = set()        # keep track of visited nodes
    queue = deque([start]) # initialize queue with start node
    traversal = []

    visited.add(start)

    while queue:
        node = queue.popleft()
        traversal.append(node)

        for neighbor in graph[node]:
            if neighbor not in visited:
                visited.add(neighbor)
                queue.append(neighbor)

    return traversal


# Example usage
if __name__ == "__main__":
    # Undirected graph represented as adjacency list
    graph = {
        0: [1, 2],
        1: [0, 3, 4],
        2: [0, 6],
        3: [1],
        4: [1],
        5: [2],
        6: [1]
    }

    start_node = 0
    result = bfs(graph, start_node)
    print("BFS Traversal:", result)

