# -*- coding: utf-8 -*-
"""Problem006.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yqQWB0KDUc4K4OVHCblPKnOu-MUK_2zN
"""

import heapq

def dijkstra(V, adj, S):
    # distances array
    dist = [float("inf")] * V
    dist[S] = 0

    # priority queue -> (distance, node)
    pq = [(0, S)]

    while pq:
        d, node = heapq.heappop(pq)

        # Skip if we already found a shorter path
        if d > dist[node]:
            continue

        for nei, w in adj[node]:
            if d + w < dist[nei]:
                dist[nei] = d + w
                heapq.heappush(pq, (dist[nei], nei))

    return dist


# Example
V = 3
adj = [
    [[1, 1], [2, 6]],   # neighbors of 0
    [[2, 3], [0, 1]],   # neighbors of 1
    [[1, 3], [0, 6]]    # neighbors of 2
]
S = 2

print(dijkstra(V, adj, S))  # Output: [4, 3, 0]

