# -*- coding: utf-8 -*-
"""problem016.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15p40o3RQChvIUgcy0gf5KHKVc8Oe5Ju5
"""

from collections import deque
from typing import List

class Solution:
    def solve(self, board: List[List[str]]) -> None:

        m = len(board)
        n = len(board[0])

        borderQueue = deque()

        for i in range(m):
            if board[i][0] == 'O':
                borderQueue.append((i,0))
            if board[i][n-1] == 'O':
                borderQueue.append((i,n-1))

        for i in range(n):
            if board[0][i] == 'O':
                borderQueue.append((0,i))
            if board[m-1][i] == 'O':
                borderQueue.append((m-1,i))


        directions = [(1,0),(0,1),(-1,0),(0,-1)]

        while borderQueue:
            x, y = borderQueue.popleft()
            board[x][y] = 'C'
            for dx, dy in directions:
                newX, newY = x + dx, y + dy
                if 0 <= newX < m and 0 <= newY < n and board[newX][newY] == 'O':
                    borderQueue.append((newX,newY))
                    board[newX][newY] = 'C'

        for i in range(m):
            for j in range(n):
                if board[i][j]=='O':
                    board[i][j]='X'
                if board[i][j]=='C':
                    board[i][j]='O'


board = [
    ["X","X","X","X"],
    ["X","O","O","X"],
    ["X","X","O","X"],
    ["X","O","X","X"]
]
Solution().solve(board)
print(board)

board = [["O","X","O","O","X"]]
Solution().solve(board)
print(board)

board = [
    ["O","O","O"],
    ["O","O","O"],
    ["O","O","O"]
]
Solution().solve(board)
print(board)


board = [["O"]]
Solution().solve(board)
print(board)