# -*- coding: utf-8 -*-
"""problem008.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cZT9lC-UbIIFTUl0ofMxhI_Ph6sIaBWw
"""

# Path With Minimum Effort

# You are a hiker preparing for an upcoming hike. You are given heights, a 2D array of size rows x columns, where heights[row][col] represents the height of the cell (row, col). You are situated in the top-left cell, (0, 0), and you hope to travel to the bottom-right cell, (rows-1, columns-1) (i.e.,0-indexed). You can move up, down, left, or right, and you wish to find a route that requires the minimum effort.

# A route's effort is the maximum absolute difference in heights between two consecutive cells of the route.


import heapq

def brute_force_min_effort(heights):
    rows, cols = len(heights), len(heights[0])
    destination = (rows - 1, cols - 1)
    min_effort = float('inf')

    def dfs(x, y, effort_so_far, visited):
        nonlocal min_effort
        if (x, y) == destination:
            min_effort = min(min_effort, effort_so_far)
            return

        visited.add((x, y))

        for dx, dy in [(1,0), (0,1), (-1,0), (0,-1)]:
            nx, ny = x + dx, y + dy
            if 0 <= nx < rows and 0 <= ny < cols and (nx, ny) not in visited:
                diff = abs(heights[nx][ny] - heights[x][y])
                dfs(nx, ny, max(effort_so_far, diff), visited)

        visited.remove((x, y))  # backtrack

    dfs(0, 0, 0, set())
    return min_effort


def path_with_minimum_effort(heights):
    rows = len(heights)
    cols = len(heights[0])

    directions = [(1, 0), (0, 1), (-1, 0), (0, -1)]

    # Min-heap to track the minimum effort
    min_heap = [(0, 0, 0)]  # (effort, x, y)

    # 2D array to store the minimum effort to reach each cell
    effort_to_reach = [[float('inf')] * cols for _ in range(rows)]
    effort_to_reach[0][0] = 0

    while min_heap:
        # Get the current cell and the effort to reach it
        curr_effort, x, y = heapq.heappop(min_heap)

        # If we reached the bottom-right corner, return the effort
        if x == rows - 1 and y == cols - 1:
            return curr_effort

        # Explore the neighboring cells
        for dx, dy in directions:
            new_x, new_y = x + dx, y + dy

            # Check if the new coordinates are within bounds
            if 0 <= new_x < rows and 0 <= new_y < cols:
                # Calculate the effort needed to move to the neighbor
                new_effort = max(curr_effort, abs(heights[new_x][new_y] - heights[x][y]))

                # If we found a path with less effort to reach (new_x, new_y), update and push to the heap
                if new_effort < effort_to_reach[new_x][new_y]:
                    effort_to_reach[new_x][new_y] = new_effort
                    heapq.heappush(min_heap, (new_effort, new_x, new_y))

    return -1

heights = [[1,2,2],[3,8,2],[5,3,5]]
print(path_with_minimum_effort(heights))
print(brute_force_min_effort(heights))