# -*- coding: utf-8 -*-
"""problem017.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Zc_DTT5fQRVg6wOjUp7IPRLS8ypHSbo
"""

from collections import deque
from typing import List

class Solution:
    def numEnclaves(self, grid: List[List[int]]) -> int:

        m = len(grid)
        n = len(grid[0])

        borderQueue = deque()


        for i in range(m):
            if grid[i][0] == 1:
                borderQueue.append((i,0))
            if grid[i][n-1] == 1:
                borderQueue.append((i,n-1))


        for i in range(n):
            if grid[0][i] == 1:
                borderQueue.append((0,i))
            if grid[m-1][i] == 1:
                borderQueue.append((m-1,i))



        directions = [(1,0),(0,1),(-1,0),(0,-1)]

        while borderQueue:
            x, y = borderQueue.popleft()
            grid[x][y] = 2
            for dx, dy in directions:
                newX, newY = x + dx, y + dy
                if 0 <= newX < m and 0 <= newY < n and grid[newX][newY] == 1:
                    borderQueue.append((newX,newY))
                    grid[newX][newY] = 2

        count=0

        for i in range(m):
            for j in range(n):
                if grid[i][j]==1:
                    count+=1

        return count

# Create an instance of the solution
sol = Solution()

# Test Case 1
grid1 = [
  [0,0,0,0],
  [1,0,1,0],
  [0,1,1,0],
  [0,0,0,0]
]
print(sol.numEnclaves([row[:] for row in grid1]))  # Expected: 3

# Test Case 2
grid2 = [
  [0,1,1,0],
  [0,0,1,0],
  [0,0,1,0],
  [0,0,0,0]
]
print(sol.numEnclaves([row[:] for row in grid2]))  # Expected: 0

# Test Case 3
grid3 = [
  [1,1,1,1],
  [1,0,0,1],
  [1,0,0,1],
  [1,1,1,1]
]
print(sol.numEnclaves([row[:] for row in grid3]))  # Expected: 0

# Test Case 4
grid4 = [
  [0,0,0,0,0],
  [0,1,1,1,0],
  [0,1,0,1,0],
  [0,1,1,1,0],
  [0,0,0,0,0]
]
print(sol.numEnclaves([row[:] for row in grid4]))  # Expected: 8

