# -*- coding: utf-8 -*-
"""Problem003.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EKQCjr1Qm_f6PVpXxrBwjj2PhhUQG9pT
"""

from collections import deque

def rottenOranges(grid):

  q = deque()
  fresh_oranges=0
  minutes=0

  r = len(grid)
  c = len(grid[0])

  for i in range(r):
    for j in range(c):
      curr=grid[i][j]
      if curr==2:
        q.append((i,j))
      if curr==1:
        fresh_oranges+=1

  directions = [(1,0),(0,1),(-1,0),(0,-1)]

  while q and fresh_oranges > 0:
    for _ in range(len(q)):
      x , y = q.popleft()
      for dx , dy in directions:
        newX , newY = x + dx, y + dy
        if 0 <= newX < r and 0 <= newY < c and grid[newX][newY] == 1:
          grid[newX][newY] = 2
          q.append((newX , newY))
          fresh_oranges-=1
    minutes+=1
    # for i in grid:
    #   print(i)
    # print(end="\n")

  if fresh_oranges == 0:
    return minutes
  else:
    return -1


grid = [ [2,1,1] , [1,1,0] , [1,0,1] ]

print(rottenOranges(grid))
print(rottenOranges( [ [2,1,1] , [1,1,0] , [0,1,1] ] ))

