# -*- coding: utf-8 -*-
"""Problem002.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Lb2QwsLuV0Ysa1owTMOLwrZnGqqXamj
"""

from collections import deque

def bfs(adj,start,visited):
  q = deque()
  q.append(start)

  while q:
    curr=q.popleft()
    for i in adj[curr]:
      if not visited[i]:
        q.append(i)
        visited[i]=True
  # print(visited)

def countProvinces(adj,v):
  visited = [False]*v
  provinces=0

  for i in range(v):
    if not visited[i]:
      provinces+=1
      bfs(adj,i,visited)

  return provinces

adj = {
        0: [1],
        1: [0, 2],
        2: [1],
        3: [4],
        4: [3]
    }

countProvinces(adj,5)

