# -*- coding: utf-8 -*-
"""Problem007.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fXqgOd9iT_v2A3cFR3xYLh045ut6KlXn
"""

from collections import deque

def shortestDistance(grid, source, destination):
    r, c = len(grid), len(grid[0])

    if grid[source[0]][source[1]] == 0 or grid[destination[0]][destination[1]] == 0:
        return "Please enter a valid source"

    directions = [(1,0),(0,1),(-1,0),(0,-1)]
    q = deque()
    q.append((source[0], source[1], 0))
    visited = set([source])

    while q:
        x, y, dist = q.popleft()

        if (x, y) == destination:
            return dist


        for dx, dy in directions:
            newX, newY = x + dx, y + dy
            new = (newX, newY)
            if 0 <= newX < r and 0 <= newY < c and grid[newX][newY] == 1 and new not in visited:
                visited.add(new)
                q.append((newX, newY, dist + 1))

    return -1


grid = [[1, 1, 1, 1],
        [1, 1, 0, 1],
        [1, 1, 1, 1],
        [1, 1, 0, 0],
        [1, 0, 0, 1]]

source = (0, 1)
destination = (2, 2)

print(shortestDistance(grid, source, destination))

grid = [[1, 1, 0],
        [0, 0, 0],
        [1, 1, 1]]

source = (0, 0)
destination = (2, 2)

print(shortestDistance(grid, source, destination))

