# -*- coding: utf-8 -*-
"""problem013.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1niQLfZM7UPBC-SjTusxmu4BCCTTtG8iW
"""

from collections import deque

def flood_fill(grid, sr, sc, new_colour):

  original = grid[sr][sc]
  r = len(grid)
  c = len(grid[0])

  if original == new_colour:
    return

  grid[sr][sc] = new_colour

  q = deque()
  q.append((sr,sc))

  directions = [(1,0),(0,1),(-1,0),(0,-1)]

  while q:
    x, y = q.popleft()
    for dx, dy in directions:
      newX, newY = x + dx, y + dy
      if 0 <= newX < r and 0 <= newY < c and grid[newX][newY] == original:
        grid[newX][newY] = new_colour
        q.append((newX,newY))

grid = [[1,1,1],[1,1,0],[1,0,1]]
flood_fill(grid,1,1,2)
print(grid)

grid = [[1,1,1],[2,2,0],[2,2,2]]
flood_fill(grid, 2, 0, 3)
print(grid)

