# -*- coding: utf-8 -*-
"""Problem012.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oO2gVpejcy6WfKfIPAHJ1wj-moJ0ng49
"""

# Depth First Search (DFS)

# Problem Statement: Given an undirected graph, return a vector of all nodes by traversing the graph using depth-first search (DFS).

# Pre-req: Recursion, Graph Representation


def dfs(graph, start, visited=None):
    if visited is None:
        visited = set()   # keep track of visited nodes
    visited.add(start)
    traversal = [start]   # current node added to traversal

    for neighbor in graph[start]:
        if neighbor not in visited:
            traversal.extend(dfs(graph, neighbor, visited))  # recursive call

    return traversal


# Example usage
if __name__ == "__main__":
    # Undirected graph represented as adjacency list
    graph = {
        0: [1, 2],
        1: [0, 3, 4],
        2: [0, 5],
        3: [1],
        4: [1],
        5: [2, 6],
        6: [5]
    }

    start_node = 0
    result = dfs(graph, start_node)
    print("DFS Traversal:", result)

