# -*- coding: utf-8 -*-
"""Problem004.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NmXEJlWIf0Pnk_hKk9rP8U2jDLYEZos5
"""

from collections import deque

def nearest1Distance(grid):
    n = len(grid)
    m = len(grid[0])
    dist = [[-1] * m for _ in range(n)]   # store distances
    q = deque()

    # Step 1: Initialize queue with all cells having 1
    for i in range(n):
        for j in range(m):
            if grid[i][j] == 1:
                dist[i][j] = 0
                q.append((i, j))

    # 4 possible moves (up, down, left, right)
    directions = [(0,1), (0,-1), (1,0), (-1,0)]

    # Step 2: BFS
    while q:
        x, y = q.popleft()
        for dx, dy in directions:
            nx, ny = x + dx, y + dy
            if 0 <= nx < n and 0 <= ny < m and dist[nx][ny] == -1:
                dist[nx][ny] = dist[x][y] + 1
                q.append((nx, ny))

    return dist


# Example Usage
if __name__ == "__main__":
    grid = [
        [0, 0, 1],
        [0, 0, 0],
        [1, 0, 0]
    ]

    result = nearest1Distance(grid)
    print("Distance Grid:")
    for row in result:
        print(row)

